# -*- coding: utf-8 -*-
"""asset_map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/cangurosorte/dependency-map/blob/main/asset_map.ipynb

## Requirements with exact version
### python install via pip
- dash==2.17.0
- jaal==0.1.7
- pandas==2.2.2

## Import Packages
"""

import pandas as pd
from jaal import Jaal
#from jaal.datasets import load_got
from dash import html as html

"""# Variables

"""

#sz_file_path = "csv/dependecy_report.csv"
sz_file_path = "csv/dependency.csv"
#nodes = "csv/refined_study_2/node_filtred_refined.csv"
remove_string = "Unscanned Device"
tcp_webbrowser_port = 8071

"""## Pandas dataframe load
Import CSV Dependency File from Migration Center -> Stratozone
"""

sz_file_csv = pd.read_csv(sz_file_path,usecols=['initiatingDeviceName','receivingDeviceName','receivingPort','connectionCount'],
                          header=0,
                        #dtype={'initiatingDeviceName': 'str', 'receivingDeviceName': 'str', 'receivingPort': int, 'connectionCount': int }
                        )

"""## Load Auxiliary Data"""

nodes_df = pd.read_csv(nodes, header=0)

nodes_df.head(3)

"""## Port Filter

"""

filtred_ports = sz_file_csv[(sz_file_csv["receivingPort"] != '22' ) & (sz_file_csv["receivingPort"] != '3389' ) & (sz_file_csv["receivingPort"] != '53' )]

"""### Remove List in ReceivingDeviceName and initiatingDeviceName"""

def remove_from_initiating_and_recieving(substring_to_remove, df):
    filter_dst = df['receivingDeviceName'].str.contains(substring_to_remove)
    filtred_df_dst = df[~filter_dst]
    filter_src = filtred_df_dst['initiatingDeviceName'].str.contains(substring_to_remove)
    filtred_df = filtred_df_dst[~filter_src]
    return filtred_df

filtred_ports

tmp_df = filtred_ports
remove_list = ["Unscanned Device", "P0PSWVCOM01","P0PSWFADS02","P0PSWVADS01"]

string1 = "Unscanned Device"
#string2 = "P0PSWVCOM01"

post_filter_df = remove_from_initiating_and_recieving(string1,tmp_df)
#post_filter_df = remove_from_initiating_and_recieving(string2,post_filter_df)

post_filter_df

"""## Dataframe Column rename
Adjust to better work wi JAAL python Module
"""

df = post_filter_df.rename(
    columns={
        "initiatingDeviceName": "from",
        "receivingDeviceName": "to",
        "connectionCount": "weight"
    }
)

"""## Summarization"""

df_raw = df.groupby(['from','to'], as_index=False)['weight'].sum()

df_grouped = df_raw[df_raw['weight'] >= 1 ]

len(df_grouped)

nodes_df

df_grouped["type"] = "Undirected"
df_grouped

"""## Plot
The default method was adjusted doe the number of interactions to stabilize.
"""

#Jaal(edge_df=df_grouped,node_df=nodes_df).plot(port=8085,directed=False, vis_opts={'height': '1290px','weight': '1100px','interaction':{'hover': True},'physics':{'solver' : 'repulsion'}})
# Jaal(edge_df=df_grouped).plot(port=8085)
edge_df = df_grouped
node_df = nodes_df
Jaal(edge_df=edge_df,node_df=node_df).plot(port=tcp_webbrowser_port,directed=False, vis_opts={'height': '1290px','weight': '1100px','interaction':{'hover': True},'physics':{'solver' : 'repulsion'}})